### ISSUE TITLE
The gui truncates lat lon to 2 decimals

### ISSUE THREAD

**Issue by JacquesGr** [moshe-braner/Open-Glider-Network-Groundstation#12]
The gui truncates lat lon to 2 decimals so when saving the data in json.conf is also truncated to 2 decimals.

**Comment by moshe-braner** [comment]
2 decimals on the degrees, e.g., 34.56N?  It interprets the entered string as a "float", so should keep at least two more digits than that?

**Comment by moshe-braner** [comment]
Fixed
