### ISSUE TITLE
Can not regsiter on OGN with MB106

### ISSUE THREAD

**Issue by schenlap** [moshe-braner/Open-Glider-Network-Groundstation#15]
With MB106 i can not register in OGN. The Log from USB displays:
```
0 recvd, 0 trkd, 0 waiting, oldest: -1
Registering OGN...

OGN connection failed

server registration failed!
0 recvd, 0 trkd, 0 waiting, oldest: -1
```
Wifi connection ist OK, how can I debug further?

config looks like:
```
  },
  "aprs": {
    "callsign": "Mxxxx",
    "server": "aprs.glidernet.org",
    "port": 14580,
    "band": 1,
    "protocol_1": 0,
    "protocol_2": 1,
    "debug": false,
    "debugport": 12000,
    "itrackbit": false,
    "istealthbit": false,
    "range": 100
  },
```

**Comment by schenlap** [comment]
`"server": "aprs-pool.glidernet.org",`
seems to work.

**Comment by moshe-braner** [comment]
Sorry, I didn't notice this open issue until today.  The plain "aprs.glidernet.org" still works for me, so I don't know why it didn't work for you.  But interesting that you can choose "aprs-pool.glidernet.org".  I am still having a problem reboots that may be related to unreliable internet connection at our test location, posted MB107 but will probably have to revise that again.
