### ISSUE TITLE
T-Beam does not charge battery

### ISSUE THREAD

**Issue by lkangas** [moshe-braner/Open-Glider-Network-Groundstation#20]
When plugging a 18650 battery, its voltage is reported on the screen and to the base station, but the voltage stays low forever even when plugged in micro USB. Is there a configuration to enable battery charging?

**Comment by moshe-braner** [comment]
Hi lkangas.  Sorry I didn't notice this comment until now.  Which version of the T-Beam, and which version of SoftRF?

**Comment by lkangas** [comment]
I'm using T-BEAM-AXP2101-V1.2. 

I can have a go with Meshtastic fw at some point, to rule out if it's a software config issue.

**Comment by moshe-braner** [comment]
Thanks.  Only some months ago I added code (copied from Linar's version) for the AXP2101.  Maybe it is missing some command to turn on the charging.  I will look into it.

**Comment by moshe-braner** [comment]
Fixed now, I think.  Let me know if it works for you.

**Comment by lkangas** [comment]
Excellent! I'm at the EFRY airfield now trying to set some things up, but I don't have any battery cells with me. I'll try this fix out next week.

I'm having some difficulties with the new versions, they seem to receive messages but do not send anything to APRS. Serial debug shows either "rejected too far" which is definitely not true, or say something about incorrect decryption. Happens on both SoftRF legacy senders and actual Flarms. I will carry out more tests tomorrow or day after, and open a new issue for them.

**Comment by moshe-braner** [comment]
Hi Lauri.  This conversation is going through github's "issues" area.  You
may want to join the Google Group I have set up for discussions about
SoftRF and OGNbase.  There you will see, for example, that the new version
I posted today also fixes bugs that caused decryption errors in the EU.
https://groups.google.com/g/softrf_community  - you need to ask to join,
and state a reason.

**Comment by lkangas** [comment]
MB139 successfully charges the battery now!
